CREATE TABLE IF NOT EXISTS Lead (
  id TEXT PRIMARY KEY NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  subcategory TEXT,
  country TEXT NOT NULL,
  city TEXT,
  region TEXT,
  budgetMin INTEGER NOT NULL DEFAULT 0,
  budgetMax INTEGER NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'USD',
  timeline TEXT NOT NULL,
  skills TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'direct',
  sourceUrl TEXT,
  clientName TEXT NOT NULL,
  clientCompany TEXT,
  clientEmail NOT NULL,
  clientPhone TEXT,
  clientAddress TEXT,
  clientLinkedin TEXT,
  clientWebsite TEXT,
  experienceReq TEXT,
  projectType TEXT,
  status TEXT NOT NULL DEFAULT 'OPEN',
  urgent BOOLEAN NOT NULL DEFAULT 0,
  featured BOOLEAN NOT NULL DEFAULT 0,
  views INTEGER NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO Lead VALUES ('cmr5xojfj0000syd4yjqdy1pw','Luxury Villa Interior Design — Palm Jumeirah','Premium real estate developer seeking an experienced interior designer for a 12,000 sq ft villa on Palm Jumeirah, Dubai. The project requires a contemporary yet warm aesthetic blending Middle Eastern elements with modern luxury. Deliverables include space planning, material selection, 3D renders, and full design documentation for contractor handoff.','DESIGN','Interior Design','AE','Dubai','GCC',15000,35000,'USD','8-12 weeks','Interior Design,AutoCAD,SketchUp,V-Ray,Space Planning,Material Selection','linkedin','https://linkedin.com/jobs/view/3284910285','Ahmed Al Mansouri','Emirates Luxury Properties','ahmed@emirateslux.ae','+971 50 123 4567','Office 1205, The One Tower, Sheikh Zayed Road, Dubai, UAE','https://linkedin.com/in/ahmedalmansouri','https://emirateslux.ae','Senior','One-off','OPEN',1,1,0,'2026-07-04T05:40:36.319Z','2026-07-04T05:40:36.319Z');
INSERT INTO Lead VALUES ('cmr5xojfl0001syd4vlcwrtja','Brand Identity Redesign — London Fintech Startup','Fast-growing London-based fintech startup needs a complete brand identity overhaul as they prepare for Series B funding. Looking for a senior brand designer to create a new logo, color system, typography, brand guidelines, pitch deck template, and social media kit. The brand needs to convey trust, innovation, and accessibility to a UK and European audience.','DESIGN','Brand Identity','GB','London','Europe',8000,18000,'USD','6-8 weeks','Brand Identity,Logo Design,Illustrator,Typography,Brand Guidelines,Figma','linkedin','https://linkedin.com/jobs/view/4182930175','James Whitfield','NexaPay','james@nexpay.co.uk',NULL,'Level 8, 1 Finsbury Avenue, London EC2M 2PF, UK','https://linkedin.com/in/jameswhitfield','https://nexpay.co.uk','Senior','One-off','OPEN',0,1,0,'2026-07-04T05:40:36.321Z','2026-07-04T05:40:36.321Z');
INSERT INTO Lead VALUES ('cmr5xojfm0002syd4jdca0kul','3D Product Visualization — Singapore Electronics Brand','Leading Singapore consumer electronics company needs photorealistic 3D renders for their new smart home device lineup (5 products). Renders will be used across e-commerce, social media, and print advertising. Each product needs 8 angles plus lifestyle scene compositions. Quality must match Apple/Samsung level product photography.','DESIGN','3D Visualization','SG','Singapore','Asia Pacific',6000,12000,'USD','4-6 weeks','3D Visualization,Blender,Substance Painter,Product Rendering,KeyShot,Photoshop','freelance_platform','https://www.upwork.com/jobs/3D-Product-Visualization_~01a8b2c3d4e5','Wei Lin Tan','AuraTech Singapore','weilin@auratech.sg',NULL,'71 Robinson Road, #14-01, Singapore 068895',NULL,'https://auratech.sg','Mid-level','One-off','OPEN',0,0,0,'2026-07-04T05:40:36.323Z','2026-07-04T05:40:36.323Z');
INSERT INTO Lead VALUES ('cmr5xojfo0003syd4z8x39ul2','Corporate Website Redesign — Riyadh Government Entity','Saudi government digital transformation initiative requires a complete website redesign for a major government portal. The site needs to serve citizens and businesses with information, services, and online forms. Must support Arabic/English bilingual content with RTL layout. 20+ pages, WCAG 2.1 AA compliance required. Security-focused design with modern aesthetics aligned with Vision 2030.','DESIGN','Web Design & Development','SA','Riyadh','GCC',20000,45000,'USD','12+ weeks','Web Design,UI/UX,Figma,RTL Design,Accessibility,Government Design,Wix/WordPress','government_portal','https://linkedin.com/jobs/view/5172839401','Faisal Al Otaibi','Digital Government Authority','faisal@dga.gov.sa','+966 55 876 5432','King Fahd Road, Al Olaya District, Riyadh 12211, Saudi Arabia','https://linkedin.com/in/faisalalotaibi',NULL,'Expert','One-off','OPEN',1,1,1,'2026-07-04T05:40:36.324Z','2026-07-04T05:53:55.551Z');
INSERT INTO Lead VALUES ('cmr5xojfq0004syd49su7r9ul','Product Design — NYC Smart Home Hardware','New York-based hardware startup developing a smart doorbell product needs an industrial/product designer to refine the exterior design, create photorealistic renders for crowdfunding campaign, and prepare manufacturing-ready CAD files. The design language should be minimalist, premium, and weather-resistant for outdoor use.','DESIGN','Product Design','US','New York','North America',10000,22000,'USD','8-12 weeks','Product Design,SolidWorks,Rhino,KeyShot,3D Printing,CAD,DFM','referral',NULL,'Sarah Chen','Guardian Home Inc.','sarah@guardianhome.com',NULL,NULL,NULL,NULL,'Senior','One-off','OPEN',0,0,0,'2026-07-04T05:40:36.326Z','2026-07-04T05:40:36.326Z');
INSERT INTO Lead VALUES ('cmr5xojfr0005syd4y9qtgra2','Grade A Office Fitout — DIFC Tower','International law firm expanding into Dubai International Financial Centre requires a full office fitout for 15,000 sq ft space across two floors. Includes executive offices, conference rooms, open-plan workstations, reception area, pantry, and server room. Must meet DIFC design guidelines. MEP, joinery, lighting, and furniture procurement needed. Turnkey delivery preferred.','FITOUT','Office Fitout','AE','Dubai','GCC',250000,450000,'USD','12+ weeks','Office Fitout,MEP Works,Joinery,Lighting Design,Furniture Procurement,Project Management','trade_show','https://www.big5.ae','Michael Harrington','Baker & Sterling LLP','m.harrington@baksterling.com','+971 4 567 8901','Gate Village, Building 10, DIFC, Dubai, UAE','https://linkedin.com/in/michaelharrington','https://baksterling.com','Expert','One-off','OPEN',1,1,0,'2026-07-04T05:40:36.328Z','2026-07-04T05:40:36.328Z');
INSERT INTO Lead VALUES ('cmr5xojfs0006syd49jvrx6je','Luxury Restaurant Fitout — Yas Island Abu Dhabi','High-end Japanese restaurant concept launching on Yas Island needs complete interior fitout for 8,000 sq ft space including main dining (120 covers), private dining rooms (3), sushi bar, cocktail lounge, open kitchen, and restrooms. Design direction: modern Japanese minimalism with warm wood accents, water features, and ambient lighting. Full MEP and kitchen equipment installation required.','FITOUT','Restaurant & F&B Fitout','AE','Abu Dhabi','GCC',350000,600000,'USD','12+ weeks','Restaurant Fitout,MEP Works,Joinery,Lighting Design,Kitchen Equipment,Acoustics','referral',NULL,'Khalid Al Nahyan','Sakura Hospitality Group','khalid@sakurahg.ae',NULL,NULL,NULL,NULL,'Expert','One-off','OPEN',0,1,0,'2026-07-04T05:40:36.329Z','2026-07-04T05:40:36.329Z');
INSERT INTO Lead VALUES ('cmr5xojft0007syd4d2bg0xn5','Retail Store Renovation — Jeddah Mall','International fashion brand renovating their flagship store in Red Sea Mall, Jeddah. 5,500 sq ft space needs complete interior overhaul including new display systems, fitting rooms, lighting, flooring, and signage. Must align with global brand guidelines while incorporating local design elements. Work to be completed during night shifts to avoid mall disruption.','FITOUT','Retail Fitout','SA','Jeddah','GCC',120000,200000,'USD','8-12 weeks','Retail Fitout,Joinery,Lighting Design,Display Systems,Project Management','website_scraped',NULL,'Noura Al Qahtani','Maison Mode KSA','noura@maisonmode.sa','+966 50 345 6789',NULL,NULL,NULL,'Senior','One-off','OPEN',0,0,0,'2026-07-04T05:40:36.330Z','2026-07-04T05:40:36.330Z');
INSERT INTO Lead VALUES ('cmr5xojfu0008syd450o6emv8','Villa Complete Renovation — Doha West Bay','Qatari family seeking complete renovation of a 9,000 sq ft villa in West Bay Lagoon. Scope includes structural modifications, new electrical/plumbing/HVAC systems, complete interior redesign with luxury finishes, new kitchen, bathrooms (5), and landscaping. Contemporary Arabic luxury style desired. Must handle all municipality permits.','FITOUT','Villa Renovation','QA','Doha','GCC',180000,320000,'USD','12+ weeks','Villa Renovation,MEP Works,Structural Work,Interior Finishes,Landscaping,Permits','direct',NULL,'Hamad Al Thani',NULL,'hamad.villa@gmail.com','+974 3344 5566',NULL,NULL,NULL,'Expert','One-off','OPEN',0,0,0,'2026-07-04T05:40:36.331Z','2026-07-04T05:40:36.331Z');
INSERT INTO Lead VALUES ('cmr5xojfw0009syd43v5aq2sg','Commercial Space MEP Upgrade — Sharjah Industrial Area','Manufacturing facility in Sharjah Industrial Area needs complete MEP systems upgrade for a 25,000 sq ft warehouse and office space. Includes new electrical distribution, HVAC system, fire suppression, plumbing, and data cabling. Must meet Sharjah Municipality and Civil Defense requirements. Need contractor who can handle design, supply, and installation.','FITOUT','MEP Works','AE','Sharjah','GCC',150000,280000,'USD','8-12 weeks','MEP Works,Electrical,HVAC,Plumbing,Fire Suppression,Data Cabling','direct',NULL,'Rajesh Patel','Gulf Manufacturing LLC','rajesh@gulfmfg.ae',NULL,NULL,NULL,NULL,'Senior','One-off','OPEN',1,0,0,'2026-07-04T05:40:36.333Z','2026-07-04T05:40:36.333Z');
INSERT INTO Lead VALUES ('cmr5xojfx000asyd44l8tnpvn','Business Credit Card Required — UAE Startup','Dubai-based tech startup (registered in DIFC) with 3 months of operations, AED 500K monthly revenue, looking for a business credit card with high spending limits for SaaS subscriptions, travel, and vendor payments. Interested in cards with rewards/cashback programs. Need multiple cards for team members. Already have business bank account with Emirates NBD.','CREDIT_CARD','Business Credit Card','AE','Dubai','GCC',0,0,'USD','1-2 weeks','Business Banking,Credit Assessment,Corporate Cards','linkedin','https://linkedin.com/posts/omaralrashid-credit-card-needed-activity-72839105','Omar Al Rashid','CloudBase Technologies','omar@cloudbase.ae','+971 55 234 5678','DIFC Innovation Hub, Level 3, Dubai, UAE','https://linkedin.com/in/omaralrashid',NULL,NULL,NULL,'OPEN',1,1,1,'2026-07-04T05:40:36.334Z','2026-07-04T05:46:43.143Z');
INSERT INTO Lead VALUES ('cmr5xojfy000bsyd4psv5wv71','Premium Credit Card Inquiry — Saudi Executive','Senior executive in Riyadh seeking a premium credit card with exclusive benefits including airport lounge access worldwide, travel insurance, concierge services, and golf privileges. Annual income above SAR 80,000/month. Currently holds basic cards from Al Rajhi and SABB. Looking for something with better perks and recognition. Willing to pay premium annual fee for the right card.','CREDIT_CARD','Premium Credit Card','SA','Riyadh','GCC',0,0,'USD','2-4 weeks','Premium Banking,Wealth Management,Credit Cards','direct',NULL,'Turki Al Faisal',NULL,'turki.alfaisal@gmail.com','+966 55 678 9012',NULL,NULL,NULL,NULL,NULL,'OPEN',0,0,0,'2026-07-04T05:40:36.334Z','2026-07-04T05:40:36.334Z');
INSERT INTO Lead VALUES ('cmr5xojfz000csyd4xu93y6yl','Travel Rewards Card — Qatar Airways Frequent Flyer','Doha-based aviation professional who travels 15+ times per year, mostly on Qatar Airways. Looking for a credit card that maximizes Qmiles earning and offers travel-related benefits like lounge access, travel insurance, and no foreign transaction fees. Monthly spend approximately QAR 25,000. Currently not satisfied with QNB card rewards rate.','CREDIT_CARD','Travel Rewards Card','QA','Doha','GCC',0,0,'USD','2-4 weeks','Travel Cards,Airline Partnerships,Rewards Optimization','website_scraped',NULL,'Aisha Al Kuwari','Qatar Airways','aisha.ak@qatarairways.qa',NULL,NULL,NULL,NULL,NULL,NULL,'OPEN',0,0,0,'2026-07-04T05:40:36.335Z','2026-07-04T05:40:36.335Z');
INSERT INTO Lead VALUES ('cmr5xojg0000dsyd4tff147to','Cashback Credit Card — Kuwait Family','Kuwaiti family with monthly household spend of KWD 3,000-4,000 looking for a cashback credit card that maximizes returns on groceries, fuel, dining, and online shopping. Want a card with good cashback rates (preferably 2%+ on everyday purchases) with easy redemption. Currently comparing NBK, Boubyan, and Gulf Bank options. Need unbiased comparison and recommendation.','CREDIT_CARD','Cashback Card','KW','Kuwait City','GCC',0,0,'USD','2-4 weeks','Cashback Cards,Personal Finance,Card Comparison','referral',NULL,'Fatima Al Sabah',NULL,'fatima.sabah@gmail.com','+965 6677 8899',NULL,NULL,NULL,NULL,NULL,'OPEN',0,0,0,'2026-07-04T05:40:36.336Z','2026-07-04T05:40:36.336Z');
INSERT INTO Lead VALUES ('cmr5xojg1000esyd4y36pakcj','Corporate Card Program — Bahrain Construction Firm','Mid-size construction company in Bahrain with 45 employees needing to set up a corporate card program. Need 10-15 cards for project managers and site engineers for procurement, travel, and miscellaneous expenses. Require spending controls, real-time tracking, and monthly consolidated billing. Currently using petty cash system which is inefficient. Looking for cards with good merchant acceptance across GCC.','CREDIT_CARD','Corporate Card','BH','Manama','GCC',0,0,'USD','4-6 weeks','Corporate Cards,Expense Management,Spending Controls,Business Banking','direct',NULL,'Yusuf Al Khalifa','Gulf Contracting WLL','yusuf@gulfcontracting.bh','+973 3444 5566',NULL,NULL,NULL,NULL,NULL,'OPEN',0,0,1,'2026-07-04T05:40:36.337Z','2026-07-04T05:46:31.242Z');
INSERT INTO Lead VALUES ('cmr5xojg2000fsyd4a73xs7rv','UAE Resident Searching for Credit Card — Instagram Reels Engagement','Dubai resident (Indian expat, 28, software engineer, AED 25K/month salary) actively engaging with credit card comparison content on Instagram reels and TikTok. Liked and saved 15+ credit card review videos in the past week. Shows interest in cashback cards, no annual fee options, and cards with airport lounge access. Currently has no credit card — first-time applicant. Ideal for entry-level card with good rewards.','CREDIT_CARD','Cashback Card','AE','Dubai','GCC',0,0,'USD','1-2 weeks','Credit Card Comparison,First-Time Applicant,Cashback Optimization','social_media','https://instagram.com/reel/credit-card-uae-comparison','Rahul Menon',NULL,'rahul.menon88@gmail.com','+971 50 889 1234','Dubai Marina, Dubai, UAE','https://linkedin.com/in/rahulmenon88',NULL,NULL,NULL,'OPEN',0,1,1,'2026-07-04T05:40:36.338Z','2026-07-04T05:46:23.732Z');
INSERT INTO Lead VALUES ('cmr5xojg3000gsyd4bpgi0c0g','UAE Personal Loan Inquiry — Google Ads Click','Abu Dhabi-based government employee (Emirati, 35, AED 35K/month) clicked on Google Ads for "best personal loan UAE 2026". Visited 3 loan comparison websites. Looking for a personal loan of AED 200,000 for home renovation. Wants lowest interest rate, flexible repayment period (3-5 years), and quick approval. Has no existing loans. Excellent credit history. Currently banked with ADCB.','CREDIT_CARD','Personal Loan','AE','Abu Dhabi','GCC',0,0,'USD','2-4 weeks','Personal Loan,Low Interest Rate,Government Employee','google_ads',NULL,'Saeed Al Dhaheri','Abu Dhabi Government','saeed.aldhaheri@gmail.com','+971 52 345 6789','Al Raha Beach, Abu Dhabi, UAE',NULL,NULL,NULL,NULL,'OPEN',1,1,1,'2026-07-04T05:40:36.339Z','2026-07-04T05:46:17.090Z');
INSERT INTO Lead VALUES ('cmr5xojg4000hsyd41xlm1a7x','UAE Credit Card Application — Facebook Group Post','Sharjah resident (Pakistani expat, 32, sales manager, AED 18K/month) posted in "UAE Credit Cards & Loans" Facebook group asking for recommendations on best credit card for grocery and fuel cashback. Currently comparing Mashreq Neo, FAB iCredit, and Emirates Islamic card. Wants card with no minimum salary requirement. Has been in UAE for 4 years with a stable job. First time applying for UAE credit card.','CREDIT_CARD','Cashback Card','AE','Sharjah','GCC',0,0,'USD','1-2 weeks','Cashback Cards,Grocery Rewards,Fuel Rewards','facebook_group','https://facebook.com/groups/uaecreditcards/posts/12345','Hassan Ali','Gulf Trading Co.','hassan.ali.sa@gmail.com','+971 50 777 8899','Al Nahda, Sharjah, UAE','https://linkedin.com/in/hassanali32',NULL,NULL,NULL,'OPEN',0,0,1,'2026-07-04T05:40:36.341Z','2026-07-04T05:46:08.619Z');
INSERT INTO Lead VALUES ('cmr5xojg5000isyd48nbk4ht1','UAE Car Loan Inquiry — Online Comparison Website','Dubai resident (Filipino expat, 29, nurse, AED 12K/month) browsing Bayut/CarLoan4U for car financing options. Wants to buy a Toyota Yaris 2025 model (AED 75,000). Needs car loan with low down payment (preferably 10-20%), 3-5 year tenure, and competitive interest rate. Currently banks with Dubai Islamic Bank. Has DIB salary account for 2 years. Clean banking history.','CREDIT_CARD','Car Loan','AE','Dubai','GCC',0,0,'USD','2-4 weeks','Car Loan,Auto Finance,Low Down Payment','website_scraped','https://carloan4u.ae/apply','Maria Santos','Dubai Healthcare City','maria.santos.nurse@gmail.com','+971 56 112 3344','Karama, Dubai, UAE',NULL,NULL,NULL,NULL,'OPEN',0,0,1,'2026-07-04T05:40:36.342Z','2026-07-04T05:45:57.033Z');
INSERT INTO Lead VALUES ('cmr5xojg6000jsyd4cnd32bi5','UAE Debt Consolidation Loan — LinkedIn Post Engagement','Dubai-based marketing manager (British expat, 38, AED 40K/month) engaging with debt consolidation content on LinkedIn and financial blogs. Has 3 existing credit cards with total outstanding of AED 85,000 across Emirates NBD, ADIB, and Mashreq. Paying high interest (3.5% monthly). Looking for a single personal loan to consolidate all debts at lower interest rate (around 4-5% flat per annum). Wants to reduce monthly EMI burden.','CREDIT_CARD','Debt Consolidation','AE','Dubai','GCC',0,0,'USD','1-2 weeks','Debt Consolidation,Balance Transfer,Loan Restructuring','linkedin','https://linkedin.com/posts/jamesdebt-need-consolidation-uae','James Mitchell','Ogilvy MENA','james.mitchell@ogilvy.com','+971 55 444 5566','DIFC, Dubai, UAE','https://linkedin.com/in/jamesmitchell38','https://ogilvy.com/mena',NULL,NULL,'OPEN',1,1,2,'2026-07-04T05:40:36.343Z','2026-07-04T05:45:37.998Z');
INSERT INTO Lead VALUES ('cmr5xojg8000ksyd4aoyb57te','UAE Premium Credit Card — TikTok Reels Viewer','Dubai Marina resident (Lebanese expat, 31, real estate broker, AED 50K+/month commission-based income) watching premium credit card review reels on TikTok. Saved videos about Emirates NBD Infinite, Citi Prestige, and ADCB Travel card. Wants a premium card with airport lounge access, hotel upgrades, dining privileges, and high credit limit. Travels internationally 6+ times per year. Currently holds a basic ADCB card. Willing to pay AED 3,000+ annual fee for the right card.','CREDIT_CARD','Premium Credit Card','AE','Dubai','GCC',0,0,'USD','2-4 weeks','Premium Cards,Lounge Access,Travel Perks,High Net Worth','social_media','https://tiktok.com/@uaefinance/credit-card-reviews','Nadia Khoury','Betterhomes','nadia.khoury@gmail.com','+971 55 999 0011','Dubai Marina, Dubai, UAE','https://linkedin.com/in/nadiakhoury31',NULL,NULL,NULL,'OPEN',0,0,2,'2026-07-04T05:40:36.345Z','2026-07-04T05:44:48.045Z');
INSERT INTO Lead VALUES ('cmr5xojg9000lsyd4vbpx8zrj','UAE Business Credit Card — Google Search for "Business Credit Card UAE"','Dubai-based SME owner (Jordanian expat, 42, runs IT services company with AED 2M annual revenue, 12 employees) searching Google for business credit cards in UAE. Company registered in DED Dubai. Needs 3-5 business credit cards for senior staff with AED 50K-100K limits each. Monthly business expenses: AED 150K+ on cloud services, marketing, travel. Currently using personal cards and getting accounting headaches. Banked with Mashreq.','CREDIT_CARD','Business Credit Card','AE','Dubai','GCC',0,0,'USD','2-4 weeks','Business Credit Card,Corporate Cards,Expense Management,SME Banking','google_ads',NULL,'Tariq Aburumman','TechBridge Solutions FZCO','tariq@techbridge.ae','+971 50 666 7788','Dubai Silicon Oasis, Dubai, UAE','https://linkedin.com/in/tariqaburumman','https://techbridge.ae',NULL,NULL,'OPEN',0,1,1,'2026-07-04T05:40:36.345Z','2026-07-04T05:45:10.620Z');
INSERT INTO Lead VALUES ('cmr5xojga000msyd45kk84qaz','UAE Gold Loan Inquiry — WhatsApp Group Lead','Sharjah-based Indian family (husband 45, wife 40, both working, combined income AED 22K/month) inquiring about gold loan options in UAE through WhatsApp community group. Has 200 grams of 22K gold jewelry. Wants short-term loan (6-12 months) against gold for emergency family expense. Looking for best loan-to-value ratio and lowest interest rate. Previously used gold loan from Muthoot Finance in India. Wants similar service in UAE.','CREDIT_CARD','Gold Loan','AE','Sharjah','GCC',0,0,'USD','1 week','Gold Loan,Secured Loan,Short-Term Finance','referral',NULL,'Sunil Kumar',NULL,'sunil.kumar45@gmail.com','+971 50 333 4455','Al Rolla, Sharjah, UAE',NULL,NULL,NULL,NULL,'OPEN',1,0,2,'2026-07-04T05:40:36.346Z','2026-07-04T05:44:27.314Z');
INSERT INTO Lead VALUES ('cmr5xojgb000nsyd4wb045txt','Freight Forwarding — Dubai to Europe Regular Shipments','Dubai-based e-commerce company shipping 200+ parcels per week to UK, Germany, and France. Looking for a reliable freight forwarding partner with competitive rates, end-to-end tracking, customs clearance capability in EU, and delivery within 7-10 business days. Need both air freight (urgent orders) and sea freight (bulk stock). Currently facing delays and high costs with current provider.','LOGISTICS','Freight Forwarding','AE','Dubai','GCC',5000,15000,'USD','Monthly retainer','Freight Forwarding,Air Freight,Sea Freight,Customs Clearance,EU Regulations','freelance_platform','https://www.freightos.com/shipments/dubai-europe-regular','Rizwan Khan','DesertCart MEA','rizwan@desertcart.ae','+971 50 987 6543','Warehouse 45, Dubai Silicon Oasis, Dubai, UAE',NULL,'https://desertcart.ae','Mid-level','Ongoing','OPEN',1,1,0,'2026-07-04T05:40:36.347Z','2026-07-04T05:40:36.347Z');
INSERT INTO Lead VALUES ('cmr5xojgc000osyd4w6ee10x3','Warehousing & Storage — Riyadh Distribution Center','Riyadh-based FMCG distributor needs 10,000 sq ft warehousing space with temperature-controlled zones, racking systems, and inventory management capability. Location preferred near King Khalid International Airport or Riyadh Dry Port. Need pick-and-pack services, daily stock reports, and integration with our ERP system. Minimum 2-year lease with expansion option.','LOGISTICS','Warehousing & Storage','SA','Riyadh','GCC',8000,18000,'USD','4-6 weeks','Warehousing,Inventory Management,Temperature Control,ERP Integration,Pick & Pack','direct',NULL,'Abdullah Al Dossary','Gulf Fresh Distribution','abdullah@gulffresh.sa','+966 55 111 2233',NULL,NULL,NULL,'Senior','Ongoing','OPEN',0,0,0,'2026-07-04T05:40:36.348Z','2026-07-04T05:40:36.348Z');
INSERT INTO Lead VALUES ('cmr5xojgd000psyd4ghialz09','Cold Chain Logistics — Abu Dhabi Pharmaceuticals','Pharmaceutical company in Abu Dhabi requiring validated cold chain logistics for temperature-sensitive medical supplies (2-8°C and -20°C). Need GSP/GDP compliant transportation, temperature monitoring with IoT devices, and backup cooling systems. Distribution across UAE (monthly 50+ shipments) plus occasional GCC/regional deliveries. Must meet MOH and DHA regulatory requirements.','LOGISTICS','Cold Chain Logistics','AE','Abu Dhabi','GCC',12000,25000,'USD','Monthly retainer','Cold Chain,Pharmaceutical Logistics,GSP/GDP Compliance,IoT Monitoring,Regulatory','referral',NULL,'Dr. Hassan Al Muhairi','Gulf Pharma Industries','hassan@gulfpharma.ae',NULL,NULL,NULL,NULL,'Expert','Ongoing','OPEN',1,1,0,'2026-07-04T05:40:36.349Z','2026-07-04T05:40:36.349Z');
INSERT INTO Lead VALUES ('cmr5xojge000qsyd4bagmqf5a','E-commerce Fulfillment — Jeddah D2C Brand','Jeddah-based direct-to-consumer beauty brand growing rapidly needs end-to-end e-commerce fulfillment partner. Currently handling 500-800 orders/month, projected to reach 2,000/month in 6 months. Need warehousing, order processing, same-day packaging, last-mile delivery across Saudi Arabia (mainly KSA regions), returns management, and Shopify/Tap integration.','LOGISTICS','E-commerce Fulfillment','SA','Jeddah','GCC',3000,8000,'USD','Monthly retainer','E-commerce Fulfillment,Last-Mile Delivery,Shopify Integration,Returns Management,Packaging','direct',NULL,'Layla Bint Khalid','Desert Rose Beauty','layla@desertrose.sa','+966 50 444 5566',NULL,NULL,NULL,'Mid-level','Ongoing','OPEN',0,0,0,'2026-07-04T05:40:36.351Z','2026-07-04T05:40:36.351Z');
INSERT INTO Lead VALUES ('cmr5xojgf000rsyd473h7ge1w','Fleet Management Services — Doha Logistics Company','Doha logistics company with a fleet of 35 light and heavy vehicles seeking comprehensive fleet management solution. Need GPS tracking, fuel management, driver behavior monitoring, preventive maintenance scheduling, and insurance management. Fleet includes refrigerated trucks, flatbeds, and delivery vans. Looking to reduce operational costs by 15-20% through better fleet utilization.','LOGISTICS','Fleet Management','QA','Doha','GCC',6000,12000,'USD','Monthly retainer','Fleet Management,GPS Tracking,Fuel Management,Vehicle Maintenance,Telematics','website_scraped',NULL,'Mansoor Al Hajri','Doha Express Logistics','mansoor@dohaexpress.qa','+974 3322 1100',NULL,NULL,NULL,'Senior','Ongoing','OPEN',0,0,0,'2026-07-04T05:40:36.352Z','2026-07-04T05:40:36.352Z');
INSERT INTO Lead VALUES ('cmr5xojgg000ssyd4tjrjric5','Dubai Municipality Approval — Commercial Kitchen','New cloud kitchen facility in Al Quoz Industrial Area 3 requiring Dubai Municipality approval for food preparation and packaging operations. Space is 4,500 sq ft with 6 kitchen stations. Need complete documentation including floor plans, HVAC drawings, pest control plan, waste management plan, and food handler certifications. Must also get food trade license. Target: obtain all approvals within 3-4 weeks.','UAE_APPROVALS','Municipality Approval','AE','Dubai','GCC',3000,6000,'USD','4-6 weeks','Dubai Municipality,Food License,Commercial Kitchen,HVAC Approval,Documentation','government_portal','https://dm.gov.ae/services/food-establishment-approval','Sajid Malik','KitchenCraft Cloud Kitchens','sajid@kitchencraft.ae','+971 50 777 8899','Unit 12, Al Quoz Industrial Area 3, Dubai, UAE','https://linkedin.com/in/sajidmalik','https://kitchencraft.ae','Senior','One-off','OPEN',1,1,0,'2026-07-04T05:40:36.353Z','2026-07-04T05:40:36.353Z');
INSERT INTO Lead VALUES ('cmr5xojgh000tsyd4hg86w6uc','DCD No-Objection Certificate — Dubai Office Tower','New office fitout project in Business Bay tower requiring DCD (Dubai Civil Defense) No-Obection Certificate before starting construction works. 12,000 sq ft office space across single floor. Need fire safety drawings, evacuation plans, fire alarm system layout, sprinkler system design, and fire-rated material specifications. Previous NOC application was rejected due to insufficient documentation.','UAE_APPROVALS','DCD (Civil Defense)','AE','Dubai','GCC',4000,8000,'USD','4-6 weeks','DCD,Civil Defense,Fire Safety,Fire Alarm Systems,Sprinkler Design,Evacuation Plans','referral',NULL,'Rami Hadid','Sterling Workspace Interiors','rami@sterlingworkspace.ae','+971 55 333 4455',NULL,NULL,NULL,'Senior','One-off','OPEN',1,0,0,'2026-07-04T05:40:36.354Z','2026-07-04T05:40:36.354Z');
INSERT INTO Lead VALUES ('cmr5xojgi000usyd4cwzs8uwg','DEWA New Connection — Abu Dhabi Villa','Newly constructed villa in Al Raha Beach needing DEWA (Dubai Electricity and Water Authority) connection for electricity (capacity: 25 kVA) and water. Need complete application including site plan, electrical load calculation, MEP drawings approval, and final inspection coordination. Also need clearance certificate for the solar panel installation on the roof.','UAE_APPROVALS','DEWA','AE','Dubai','GCC',1500,3000,'USD','2-4 weeks','DEWA,Electricity Connection,Water Connection,Solar Panel Clearance,MEP Approval','direct',NULL,'Mohammed Al Suwaidi',NULL,'mohammed.suwaidi@outlook.com','+971 50 222 3344',NULL,NULL,NULL,'Mid-level','One-off','OPEN',0,0,0,'2026-07-04T05:40:36.355Z','2026-07-04T05:40:36.355Z');
INSERT INTO Lead VALUES ('cmr5xojgj000vsyd4eejbadms','Trakhees Approval — JAFZA Warehouse','Warehouse facility in JAFZA (Jebel Ali Free Zone) requiring Trakhees approval for modification of existing warehouse to include cold storage section and new loading dock. Need to submit architectural drawings, structural calculations, MEP plans, and environmental impact assessment to Trakhees (EHS Department). Also need update of the warehouse license category.','UAE_APPROVALS','Trakhees','AE','Dubai','GCC',5000,10000,'USD','6-8 weeks','Trakhees,JAFZA,EHS,Environmental Assessment,Warehouse Modification,Free Zone','direct',NULL,'Vikram Sharma','Gulf Cold Storage LLC','vikram@gulfcold.ae','+971 55 888 9900',NULL,NULL,NULL,'Senior','One-off','OPEN',0,0,0,'2026-07-04T05:40:36.356Z','2026-07-04T05:40:36.356Z');
INSERT INTO Lead VALUES ('cmr5xojgk000wsyd42cbcr4zo','ESTIDAMA Pearl Rating — Abu Dhabi Villa Project','New residential villa construction in Saadiyat Island requiring ESTIDAMA Pearl Rating certification (targeting 2-Pearl minimum). The 8,000 sq ft villa needs to comply with Abu Dhabi Urban Planning Council requirements including energy efficiency, water conservation, indoor environment quality, and materials specifications. Need a consultant to handle the full ESTIDAMA submission and coordinate with UPC reviewers.','UAE_APPROVALS','ESTIDAMA','AE','Abu Dhabi','GCC',8000,15000,'USD','8-12 weeks','ESTIDAMA,Pearl Rating,UPC,Energy Efficiency,Sustainability,Green Building','referral',NULL,'Khalid Al Mehairbi','Saadiyat Villas Development','khalid@saadiyatyillas.ae','+971 50 111 2244',NULL,NULL,NULL,'Expert','One-off','OPEN',0,1,0,'2026-07-04T05:40:36.357Z','2026-07-04T05:40:36.357Z');
INSERT INTO Lead VALUES ('cmr5xojgm000xsyd4zkwb8ud8','DTCM Tourism License — Dubai Hotel Apartment','New 25-key hotel apartment building in Dubai Marina requiring DTCM (Department of Tourism and Commerce Marketing) tourism license and classification. Building construction is 90% complete. Need assistance with DTCM application, building requirements compliance (room sizes, amenities, safety), staff training documentation, and final inspection coordination. Target: 3-star deluxe classification.','UAE_APPROVALS','DTCM','AE','Dubai','GCC',6000,12000,'USD','6-8 weeks','DTCM,Tourism License,Hotel Classification,Dubai Tourism,Regulatory Compliance','direct',NULL,'Ahmed Bukhari','Marina Stay Hospitality','ahmed@marinastay.ae','+971 50 999 0011',NULL,NULL,NULL,'Senior','One-off','OPEN',0,0,0,'2026-07-04T05:40:36.358Z','2026-07-04T05:40:36.358Z');
INSERT INTO Lead VALUES ('cmr5xojgn000ysyd4glseovw0','ADCD Fire Safety Approval — Abu Dhabi Mall Retail Space','New retail store fitout in Abu Dhabi Mall requiring Abu Dhabi Civil Defense (ADCD) fire safety approval. 2,500 sq ft space including display area, storage room, and small office. Need fire safety drawings, fire-rated partition specifications, emergency lighting plan, and fire extinguisher placement layout. Must comply with Abu Dhabi Civil Defense Code and mall management requirements.','UAE_APPROVALS','ADCD (Abu Dhabi Civil Defense)','AE','Abu Dhabi','GCC',2500,5000,'USD','2-4 weeks','ADCD,Civil Defense,Fire Safety,Retail Compliance,Abu Dhabi Regulations','website_scraped',NULL,'Diana Michaels','Luxe Boutique AD','diana@luxeboutique.ae',NULL,NULL,NULL,NULL,'Mid-level','One-off','OPEN',1,0,0,'2026-07-04T05:40:36.360Z','2026-07-04T05:40:36.360Z');
INSERT INTO Lead VALUES ('cmr5xojgo000zsyd4jkbcmoy5','UK E-commerce Brand Expanding to Dubai — Free Zone Company Formation','London-based e-commerce company with £2M annual revenue seeking to establish a Dubai free zone company for Middle East distribution. Need complete setup including trade license, virtual office, corporate bank account, and 2 investor visas. Currently shipping to UAE via DHL and want local presence to reduce logistics costs by 40%.','DUBAI_BUSINESS_SETUP','Free Zone Company Formation','GB','London','Europe',5000,12000,'USD','4-6 weeks','Company Formation,Free Zone Setup,Corporate Banking,Investor Visa,PRO Services','linkedin','https://linkedin.com/posts/jameswilson_uae-expansion-activity-7291846','James Wilson','NovaBrand Commerce Ltd','james@novabrand.co.uk','+44 20 7946 0958','14th Floor, The Shard, 32 London Bridge St, London SE1 9SG, UK','https://linkedin.com/in/jameswilson-ecom','https://novabrand.co.uk','Senior','One-off','OPEN',1,1,1,'2026-07-04T05:40:36.360Z','2026-07-04T05:51:47.289Z');
INSERT INTO Lead VALUES ('cmr5xojgp0010syd4y6lgscau','Indian IT Services Firm — Mainland Company + Golden Visa for Dubai Office','Mumbai-based IT services company (120 employees) planning to open a mainland Dubai office in Business Bay. Require full business setup including trade license, Ejari, 5 employment visas, golden visa for the founder, and corporate bank account with Emirates NBD. Have already shortlisted 3 office spaces and are ready to proceed immediately.','DUBAI_BUSINESS_SETUP','Mainland Company Setup','IN','Mumbai','South Asia',8000,18000,'USD','6-8 weeks','Mainland License,Ejari,Employment Visa,Golden Visa,Corporate Banking,PRO Services','linkedin','https://linkedin.com/posts/rajeshpatel_dubai-office-setup-activity-8392714','Rajesh Patel','TechVista Solutions Pvt Ltd','rajesh@techvista.in','+91 22 4857 9300','1201, Lodha Supremus, Senapati Bapat Marg, Worli, Mumbai 400013, India','https://linkedin.com/in/rajeshpatel-techvista','https://techvista.in','Expert','One-off','OPEN',0,1,2,'2026-07-04T05:40:36.361Z','2026-07-04T06:06:43.083Z');
CREATE INDEX IF NOT EXISTS idx_lead_category ON Lead(category);
CREATE INDEX IF NOT EXISTS idx_lead_country ON Lead(country);
CREATE INDEX IF NOT EXISTS idx_lead_region ON Lead(region);
CREATE INDEX IF NOT EXISTS idx_lead_status ON Lead(status);
CREATE INDEX IF NOT EXISTS idx_lead_source ON Lead(source);
